//
// Created by karim on 10/6/2023.
//

#ifndef ETHERNET_PARSER_ETHERNETPACKETFACTORYIMPL_H
#define ETHERNET_PARSER_ETHERNETPACKETFACTORYIMPL_H


class EthernetPacketFactoryImpl {

};


#endif //ETHERNET_PARSER_ETHERNETPACKETFACTORYIMPL_H
